// ============================================
// ESP Export Formats
// ============================================

interface EmailContent {
  subjectLine: string;
  previewText?: string;
  bodyHtml: string;
  ctaText?: string;
  ctaUrl?: string;
}

interface ExportOptions {
  brandName: string;
  emailType: string;
  includeTracking?: boolean;
}

// ============================================
// Klaviyo Export
// ============================================

export const exportToKlaviyo = (
  content: EmailContent,
  options: ExportOptions
): string => {
  // Klaviyo uses their own template language with variables
  const template = `<!--
  Klaviyo Email Template
  Brand: ${options.brandName}
  Type: ${options.emailType}
  Generated by Swayleo
-->

{% if preview_text %}
<div style="display:none;font-size:1px;color:#ffffff;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;">
  ${content.previewText || '{{ preview_text }}'}
</div>
{% endif %}

<table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#f8fafc;">
  <tr>
    <td align="center" style="padding:40px 20px;">
      <table width="600" cellpadding="0" cellspacing="0" border="0" style="background-color:#ffffff;border-radius:12px;">
        <!-- Header -->
        <tr>
          <td style="padding:40px 40px 20px;">
            <img src="{{ organization.logo }}" alt="{{ organization.name }}" style="max-height:48px;" />
          </td>
        </tr>
        
        <!-- Body -->
        <tr>
          <td style="padding:20px 40px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:16px;line-height:1.6;color:#374151;">
            ${convertToKlaviyoHtml(content.bodyHtml)}
          </td>
        </tr>
        
        ${content.ctaText ? `
        <!-- CTA -->
        <tr>
          <td style="padding:20px 40px 40px;">
            <table cellpadding="0" cellspacing="0" border="0">
              <tr>
                <td style="background-color:#6366f1;border-radius:8px;">
                  <a href="${content.ctaUrl || '{{ event.url }}'}" style="display:inline-block;padding:14px 28px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:16px;font-weight:600;color:#ffffff;text-decoration:none;">
                    ${content.ctaText}
                  </a>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        ` : ''}
        
        <!-- Footer -->
        <tr>
          <td style="padding:20px 40px;border-top:1px solid #e2e8f0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:12px;color:#94a3b8;text-align:center;">
            <p style="margin:0 0 10px;">{{ organization.name }}</p>
            <p style="margin:0 0 10px;">{{ organization.address }}</p>
            <p style="margin:0;">
              <a href="{{ unsubscribe }}" style="color:#94a3b8;">Unsubscribe</a>
              {% if can_manage_preferences %} | <a href="{{ manage_preferences }}" style="color:#94a3b8;">Manage Preferences</a>{% endif %}
            </p>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>`;

  return template;
};

// Convert HTML to Klaviyo-friendly format
const convertToKlaviyoHtml = (html: string): string => {
  return html
    .replace(/\{\{(\w+)\}\}/g, '{{ $1 }}') // Preserve/format variables
    .replace(/<p>/g, '<p style="margin:0 0 16px;">')
    .replace(/<h1>/g, '<h1 style="margin:0 0 16px;font-size:28px;font-weight:700;color:#111827;">')
    .replace(/<h2>/g, '<h2 style="margin:0 0 12px;font-size:22px;font-weight:600;color:#111827;">')
    .replace(/<a /g, '<a style="color:#6366f1;text-decoration:underline;" ');
};

// ============================================
// Mailchimp Export
// ============================================

export const exportToMailchimp = (
  content: EmailContent,
  options: ExportOptions
): string => {
  // Mailchimp uses merge tags
  const template = `<!--
  Mailchimp Email Template
  Brand: ${options.brandName}
  Type: ${options.emailType}
  Generated by Swayleo
-->

*|IF:MC_PREVIEW_TEXT|*
<span style="display:none;font-size:1px;color:#ffffff;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;">
  ${content.previewText || '*|MC_PREVIEW_TEXT|*'}
</span>
*|END:IF|*

<table width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#f8fafc;">
  <tr>
    <td align="center" style="padding:40px 20px;">
      <!--[if mso]>
      <table width="600" cellpadding="0" cellspacing="0" border="0">
      <tr><td>
      <![endif]-->
      
      <table width="100%" style="max-width:600px;background-color:#ffffff;border-radius:12px;" cellpadding="0" cellspacing="0" border="0">
        <!-- Header with Logo -->
        <tr>
          <td style="padding:40px 40px 20px;" mc:edit="header_logo">
            <img src="*|BRAND:LOGO|*" alt="*|LIST:COMPANY|*" style="max-height:48px;" />
          </td>
        </tr>
        
        <!-- Body Content -->
        <tr>
          <td style="padding:20px 40px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.6;color:#374151;" mc:edit="body_content">
            ${convertToMailchimpHtml(content.bodyHtml)}
          </td>
        </tr>
        
        ${content.ctaText ? `
        <!-- CTA Button -->
        <tr>
          <td style="padding:20px 40px 40px;" mc:edit="cta_button">
            <!--[if mso]>
            <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="${content.ctaUrl || '*|ARCHIVE|*'}" style="height:48px;v-text-anchor:middle;width:200px;" arcsize="17%" strokecolor="#6366f1" fillcolor="#6366f1">
            <w:anchorlock/>
            <center style="color:#ffffff;font-family:sans-serif;font-size:16px;font-weight:bold;">${content.ctaText}</center>
            </v:roundrect>
            <![endif]-->
            <!--[if !mso]><!-->
            <table cellpadding="0" cellspacing="0" border="0">
              <tr>
                <td style="background-color:#6366f1;border-radius:8px;">
                  <a href="${content.ctaUrl || '*|ARCHIVE|*'}" style="display:inline-block;padding:14px 28px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:16px;font-weight:600;color:#ffffff;text-decoration:none;">
                    ${content.ctaText}
                  </a>
                </td>
              </tr>
            </table>
            <!--<![endif]-->
          </td>
        </tr>
        ` : ''}
        
        <!-- Footer -->
        <tr>
          <td style="padding:20px 40px;border-top:1px solid #e2e8f0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:12px;color:#94a3b8;text-align:center;" mc:edit="footer">
            <p style="margin:0 0 10px;">*|LIST:COMPANY|*</p>
            <p style="margin:0 0 10px;">*|LIST:ADDRESS|*</p>
            <p style="margin:0;">
              <a href="*|UNSUB|*" style="color:#94a3b8;">Unsubscribe</a> | 
              <a href="*|UPDATE_PROFILE|*" style="color:#94a3b8;">Update Preferences</a>
            </p>
          </td>
        </tr>
      </table>
      
      <!--[if mso]>
      </td></tr></table>
      <![endif]-->
    </td>
  </tr>
</table>`;

  return template;
};

// Convert HTML to Mailchimp-friendly format
const convertToMailchimpHtml = (html: string): string => {
  return html
    .replace(/\{\{first_name\}\}/gi, '*|FNAME|*')
    .replace(/\{\{last_name\}\}/gi, '*|LNAME|*')
    .replace(/\{\{email\}\}/gi, '*|EMAIL|*')
    .replace(/<p>/g, '<p style="margin:0 0 16px;">')
    .replace(/<h1>/g, '<h1 style="margin:0 0 16px;font-size:28px;font-weight:700;color:#111827;">')
    .replace(/<h2>/g, '<h2 style="margin:0 0 12px;font-size:22px;font-weight:600;color:#111827;">')
    .replace(/<a /g, '<a style="color:#6366f1;text-decoration:underline;" ');
};

// ============================================
// Generic HTML Export
// ============================================

export const exportToGenericHtml = (
  content: EmailContent,
  options: ExportOptions
): string => {
  const template = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>${content.subjectLine}</title>
  <!--
    Email Template
    Brand: ${options.brandName}
    Type: ${options.emailType}
    Generated by Swayleo
  -->
  <style>
    body { margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
    .email-container { max-width: 600px; margin: 0 auto; }
    .btn { display: inline-block; padding: 14px 28px; background: #6366f1; color: white; text-decoration: none; border-radius: 8px; font-weight: 600; }
  </style>
</head>
<body style="background-color:#f8fafc;margin:0;padding:40px 20px;">
  ${content.previewText ? `
  <div style="display:none;font-size:1px;color:#ffffff;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;">
    ${content.previewText}
  </div>
  ` : ''}
  
  <table class="email-container" width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;">
    <tr>
      <td style="padding:40px;">
        ${content.bodyHtml}
        
        ${content.ctaText ? `
        <p style="margin-top:24px;">
          <a href="${content.ctaUrl || '#'}" class="btn" style="display:inline-block;padding:14px 28px;background:#6366f1;color:white;text-decoration:none;border-radius:8px;font-weight:600;">
            ${content.ctaText}
          </a>
        </p>
        ` : ''}
      </td>
    </tr>
  </table>
</body>
</html>`;

  return template;
};

// ============================================
// Export Type Definitions
// ============================================

export type ESPFormat = 'klaviyo' | 'mailchimp' | 'html';

export const ESP_FORMATS: { id: ESPFormat; name: string; icon: string; description: string }[] = [
  { 
    id: 'klaviyo', 
    name: 'Klaviyo', 
    icon: '📧',
    description: 'Optimized for Klaviyo with flow variables'
  },
  { 
    id: 'mailchimp', 
    name: 'Mailchimp', 
    icon: '🐵',
    description: 'Includes merge tags and editable regions'
  },
  { 
    id: 'html', 
    name: 'Generic HTML', 
    icon: '🌐',
    description: 'Clean HTML for any ESP'
  },
];

export const exportEmail = (
  format: ESPFormat,
  content: EmailContent,
  options: ExportOptions
): string => {
  switch (format) {
    case 'klaviyo':
      return exportToKlaviyo(content, options);
    case 'mailchimp':
      return exportToMailchimp(content, options);
    case 'html':
    default:
      return exportToGenericHtml(content, options);
  }
};

// Download helper
export const downloadExport = (content: string, filename: string): void => {
  const blob = new Blob([content], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
