import { describe, it, expect } from 'vitest';
import {
  exportToKlaviyo,
  exportToMailchimp,
  exportToGenericHtml,
  exportEmail,
  ESP_FORMATS,
} from '../espExport';

const mockContent = {
  subjectLine: 'Welcome to TestBrand!',
  previewText: 'Your journey starts here',
  bodyHtml: '<h1>Welcome</h1><p>Thanks for joining us.</p>',
  ctaText: 'Shop Now',
  ctaUrl: 'https://testbrand.com/shop',
};

const mockContentNoCta = {
  subjectLine: 'Weekly Update',
  previewText: 'See what is new',
  bodyHtml: '<p>Here is your weekly update.</p>',
};

const mockOptions = {
  brandName: 'TestBrand Co',
  emailType: 'welcome',
};

describe('espExport', () => {
  describe('ESP_FORMATS', () => {
    it('has exactly 3 formats', () => {
      expect(ESP_FORMATS).toHaveLength(3);
    });

    it('includes klaviyo, mailchimp, and html', () => {
      const ids = ESP_FORMATS.map(f => f.id);
      expect(ids).toEqual(['klaviyo', 'mailchimp', 'html']);
    });

    it('all formats have id, name, icon, and description', () => {
      for (const format of ESP_FORMATS) {
        expect(format.id).toBeDefined();
        expect(format.name).toBeDefined();
        expect(format.icon).toBeDefined();
        expect(format.description).toBeDefined();
      }
    });
  });

  describe('exportToKlaviyo()', () => {
    it('includes brand name in comment', () => {
      const result = exportToKlaviyo(mockContent, mockOptions);
      expect(result).toContain('Brand: TestBrand Co');
    });

    it('includes email type in comment', () => {
      const result = exportToKlaviyo(mockContent, mockOptions);
      expect(result).toContain('Type: welcome');
    });

    it('includes "Generated by Swayleo" comment', () => {
      const result = exportToKlaviyo(mockContent, mockOptions);
      expect(result).toContain('Generated by Swayleo');
    });

    it('includes preview text div', () => {
      const result = exportToKlaviyo(mockContent, mockOptions);
      expect(result).toContain('Your journey starts here');
    });

    it('includes Klaviyo template variables', () => {
      const result = exportToKlaviyo(mockContent, mockOptions);
      expect(result).toContain('{{ organization.logo }}');
      expect(result).toContain('{{ organization.name }}');
      expect(result).toContain('{{ unsubscribe }}');
    });

    it('includes CTA when provided', () => {
      const result = exportToKlaviyo(mockContent, mockOptions);
      expect(result).toContain('Shop Now');
      expect(result).toContain('https://testbrand.com/shop');
    });

    it('omits CTA section when not provided', () => {
      const result = exportToKlaviyo(mockContentNoCta, mockOptions);
      expect(result).not.toContain('Shop Now');
    });

    it('includes unsubscribe link', () => {
      const result = exportToKlaviyo(mockContent, mockOptions);
      expect(result).toContain('Unsubscribe');
    });
  });

  describe('exportToMailchimp()', () => {
    it('includes brand name in comment', () => {
      const result = exportToMailchimp(mockContent, mockOptions);
      expect(result).toContain('Brand: TestBrand Co');
    });

    it('includes Mailchimp merge tags', () => {
      const result = exportToMailchimp(mockContent, mockOptions);
      expect(result).toContain('*|BRAND:LOGO|*');
      expect(result).toContain('*|LIST:COMPANY|*');
      expect(result).toContain('*|LIST:ADDRESS|*');
      expect(result).toContain('*|UNSUB|*');
    });

    it('includes MSO conditionals for Outlook', () => {
      const result = exportToMailchimp(mockContent, mockOptions);
      expect(result).toContain('<!--[if mso]>');
      expect(result).toContain('<![endif]-->');
    });

    it('includes mc:edit regions', () => {
      const result = exportToMailchimp(mockContent, mockOptions);
      expect(result).toContain('mc:edit="header_logo"');
      expect(result).toContain('mc:edit="body_content"');
    });

    it('converts {{first_name}} to *|FNAME|*', () => {
      const contentWithVars = {
        ...mockContent,
        bodyHtml: '<p>Hi {{first_name}}, welcome!</p>',
      };
      const result = exportToMailchimp(contentWithVars, mockOptions);
      expect(result).toContain('*|FNAME|*');
      expect(result).not.toContain('{{first_name}}');
    });

    it('converts {{last_name}} to *|LNAME|*', () => {
      const contentWithVars = {
        ...mockContent,
        bodyHtml: '<p>Dear {{last_name}},</p>',
      };
      const result = exportToMailchimp(contentWithVars, mockOptions);
      expect(result).toContain('*|LNAME|*');
    });

    it('includes CTA when provided', () => {
      const result = exportToMailchimp(mockContent, mockOptions);
      expect(result).toContain('Shop Now');
    });

    it('includes update preferences link', () => {
      const result = exportToMailchimp(mockContent, mockOptions);
      expect(result).toContain('*|UPDATE_PROFILE|*');
      expect(result).toContain('Update Preferences');
    });
  });

  describe('exportToGenericHtml()', () => {
    it('generates valid HTML5 document', () => {
      const result = exportToGenericHtml(mockContent, mockOptions);
      expect(result).toContain('<!DOCTYPE html>');
      expect(result).toContain('<html lang="en">');
      expect(result).toContain('</html>');
    });

    it('includes subject line as title', () => {
      const result = exportToGenericHtml(mockContent, mockOptions);
      expect(result).toContain('<title>Welcome to TestBrand!</title>');
    });

    it('includes brand name in comment', () => {
      const result = exportToGenericHtml(mockContent, mockOptions);
      expect(result).toContain('Brand: TestBrand Co');
    });

    it('includes preview text when present', () => {
      const result = exportToGenericHtml(mockContent, mockOptions);
      expect(result).toContain('Your journey starts here');
      expect(result).toContain('display:none');
    });

    it('includes CTA button when provided', () => {
      const result = exportToGenericHtml(mockContent, mockOptions);
      expect(result).toContain('Shop Now');
      expect(result).toContain('https://testbrand.com/shop');
    });

    it('includes body HTML', () => {
      const result = exportToGenericHtml(mockContent, mockOptions);
      expect(result).toContain('Thanks for joining us.');
    });

    it('omits CTA when not provided', () => {
      const result = exportToGenericHtml(mockContentNoCta, mockOptions);
      expect(result).not.toContain('Shop Now');
    });
  });

  describe('exportEmail()', () => {
    it('routes to Klaviyo exporter', () => {
      const result = exportEmail('klaviyo', mockContent, mockOptions);
      expect(result).toContain('Klaviyo Email Template');
    });

    it('routes to Mailchimp exporter', () => {
      const result = exportEmail('mailchimp', mockContent, mockOptions);
      expect(result).toContain('Mailchimp Email Template');
    });

    it('routes to HTML exporter', () => {
      const result = exportEmail('html', mockContent, mockOptions);
      expect(result).toContain('<!DOCTYPE html>');
    });

    it('defaults to HTML for unknown format', () => {
      const result = exportEmail('unknown' as any, mockContent, mockOptions);
      expect(result).toContain('<!DOCTYPE html>');
    });
  });
});
